#!/usr/bin/env node
/**
 * Generates small Qwik icon components from lucide-static SVGs.
 * Run: node scripts/generate-icons.mjs
 * Add new icons by adding their lucide-static file name (without .svg) to ICONS below.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ICONS = {
  Menu: "menu",
  X: "x",
  ExternalLink: "external-link",
  ArrowRight: "arrow-right",
  ArrowUpRight: "arrow-up-right",
  ChevronDown: "chevron-down",
  BookOpen: "book-open",
  Quote: "quote",
  HeartHandshake: "heart-handshake",
  Map: "map",
  Users: "users",
  Landmark: "landmark",
  Flag: "flag",
  ScrollText: "scroll-text",
  ShieldAlert: "shield-alert",
  Search: "search",
  Rss: "rss",
};

const rootDir = fileURLToPath(new URL("..", import.meta.url));
const iconsSrcDir = path.join(
  rootDir,
  "node_modules",
  "lucide-static",
  "icons",
);
const outDir = path.join(rootDir, "src", "components", "ui", "icons");

function pathsFromSvg(svg) {
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim();
  return inner
    .replace(/class="[^"]*"\s*/g, "")
    .replace(/\n\s*/g, " ")
    .replace(/\s+\/>/g, " />")
    .trim();
}

async function main() {
  await mkdir(outDir, { recursive: true });
  const exportLines = [];

  for (const [componentName, fileName] of Object.entries(ICONS)) {
    const svgPath = path.join(iconsSrcDir, `${fileName}.svg`);
    const svg = await readFile(svgPath, "utf-8");
    const inner = pathsFromSvg(svg);

    const component = `import { component$, type PropsOf } from "@builder.io/qwik";

export type IconProps = Omit<PropsOf<"svg">, "class"> & {
  class?: string;
  size?: number | string;
};

export const ${componentName} = component$<IconProps>(({ size = 20, ...props }) => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      ${inner}
    </svg>
  );
});
`;

    const fileSlug = fileName;
    await writeFile(path.join(outDir, `${fileSlug}.tsx`), component, "utf-8");
    exportLines.push(`export { ${componentName} } from "./${fileSlug}";`);
  }

  const indexContent =
    `// Generated by scripts/generate-icons.mjs from lucide-static (ISC licence).\n` +
    `// Do not edit these files by hand -- edit the ICONS list in the script and re-run it.\n\n` +
    exportLines.join("\n") +
    "\n";
  await writeFile(path.join(outDir, "index.ts"), indexContent, "utf-8");

  console.log(
    `Generated ${Object.keys(ICONS).length} icon components in ${path.relative(rootDir, outDir)}`,
  );
}

main();
